Add -b option to show bytes instead of bandwidth [3.4]

diff --git a/beegfstop b/beegfstop
--- a/beegfstop
+++ b/beegfstop
@@ -4,7 +4,7 @@
 #
 # $Title: Script to generate top-like statistics for BeeGFS I/O $
 # $Copyright: 2020 Devin Teske. All rights reserved. $
-# $FrauBSD: beegfstop/beegfstop 2020-05-05 12:03:03 -0700 freebsdfrau $
+# $FrauBSD: beegfstop/beegfstop 2020-05-05 12:11:30 -0700 freebsdfrau $
 #
 ############################################################ INFORMATION
 #
@@ -33,7 +33,7 @@ DEFAULT_INTERVAL=2 # seconds
 
 ############################################################ GLOBALS
 
-VERSION='$Version: 3.3 $'
+VERSION='$Version: 3.4 $'
 
 pgm="${0##*/}" # Program basename
 
@@ -52,6 +52,7 @@ NO_NAMES=				# -n
 NSAMPLES=				# -N num
 OUTPUT_JSON=				# -j
 RAW_VIEW=				# -r
+SHOW_BYTES=				# -b
 VIEW_CLIENT=				# -c
 VIEW_SERVER=				# -s
 VIEW_USER=				# -u (default)
@@ -88,6 +89,7 @@ usage()
 
 	printf "Usage: %s [OPTIONS]\n" "$pgm"
 	printf "Options:\n"
+	printf "$optfmt" "-b" "Show bytes instead of bandwidth."
 	printf "$optfmt" "-C" "Always enable color."
 	printf "$optfmt" "-c" "View read/write activity by client."
 	printf "$optfmt" "-h" "Print usage statement and exit."
@@ -157,8 +159,9 @@ resize()
 #
 # Process command-line options
 #
-while getopts Cchi:jN:nrsuvw flag; do
+while getopts bCchi:jN:nrsuvw flag; do
 	case "$flag" in
+	b) SHOW_BYTES=1 ;;
 	C) COLOR=1 ;;
 	c) VIEW=CLIENT VIEW_CLIENT=1 ;;
 	i) INTERVAL="$OPTARG" ;;
@@ -182,6 +185,13 @@ shift $(( $OPTIND - 1 ))
 # Process command-line arguments
 #
 [ $# -eq 0 ] || usage "Too many arguments" # NOTREACHED
+
+#
+# Prevent non-functional option combinations
+#
+if [ "$SHOW_BYTES" ]; then
+	[ ! "$OUTPUT_JSON" ] || die "-b cannot be combined with -j"
+fi
 
 #
 # Silently ignore previous view options
@@ -271,6 +281,7 @@ esac
 	BEGIN {
 		exit_status = 0 # SUCCESS
 		in_summary = 1
+		time_delta = 0 # Calculated
 		samples_left = ++nsamples
 		srand() # seed clock
 
@@ -351,8 +362,8 @@ esac
 		#
 		# Without -w, make vsz fixed-width and bar_size variable.
 		#
-		dsz = 12
-		vsz_fixed = 15 # VIEW column
+		dsz = show_bytes ? 10 : 12
+		vsz_fixed = show_bytes ? 21 : 15 # VIEW column
 		bar_size_fixed = cols <= 80 ? 11 : 21
 		if (wide_view) {
 			# Fixed-width
@@ -530,7 +541,8 @@ esac
 			value /= 1024
 		}
 		if (v ~ /\./) sub(/\.?0+$/, "", v)
-		value = sprintf("%'"'"'.2f%sB/s", value, suffixes[suffix])
+		value = sprintf("%'"'"'.2f%s%s", value, suffixes[suffix],
+			show_bytes ? "B" : "B/s")
 		return value
 	}
 
@@ -627,6 +639,11 @@ esac
 			json_out = json_add_float(json_out,
 				"write_rate", write_rate)
 			buffer_add("{" json_out "}\n")
+		} else if (show_bytes) {
+			# ST: VIEWS
+			buffer_add1("total", humanize(rw_total),
+				humanize(write_total), write_bar,
+				read_bar, humanize(read_total))
 		} else {
 			# ST: VIEWS
 			buffer_add1("total", humanize(rw_rate),
@@ -671,7 +688,7 @@ esac
 		cred_write = key_write[cred]
 		cred_rw = cred_read + cred_write
 
-		read_rate = cred_read / interval
+		read_rate = cred_read / time_delta
 		if (read_total > 0)
 			read_bar_pct = cred_read / read_total
 		else
@@ -715,6 +732,11 @@ esac
 			json_out = json_add_float(json_out,
 				"write_rate", write_rate)
 			buffer_add("{" json_out "}\n")
+		} else if (show_bytes) {
+			# ST: VIEWDATA
+			buffer_add1(cred, humanize(cred_rw),
+				humanize(cred_write), write_bar,
+				read_bar, humanize(cred_read))
 		} else {
 			# ST: VIEWDATA
 			buffer_add1(cred, humanize(rw_rate),
